const fs = require('fs');

const ICONS_FOLDER = './src/client/modules/common/Icon/svg';
const GENERATED_FILE = './src/client/modules/common/Icon/IconType.ts';

module.exports = function generateIconType() {
    return new Promise((resolve, reject) => {
        fs.readdir(ICONS_FOLDER, (err, files) => {
            let iconTypes = files.map(file => file.replace('.svg', ''));
            let dictionary = iconTypes.reduce((res, cur) => {
                let key = cur.toUpperCase()
                    .replace('-', '_');
                return Object.assign({ [key]: cur }, res);
            }, {});

            let fileText =
`/**
 * This file autogenerated. Don't change it manually
 */

enum IconType {
    ${Object.keys(dictionary)
        .map((key) => {
            return `${key} = '${dictionary[key]}'`
        })
        .join(',\n    ')
    }
}

export { IconType };
`;

            fs.writeFile(GENERATED_FILE, fileText, (err) => {
                err ? reject(err) : resolve();
            });
        })
    });
};
